export const resumeData = {
  personalInfo: {
    fullName: "Sarthak Shirsat",
    headline: "Senior Product Manager",
    email: "sarthakgshirsat62@gmail.com",
    phone: "+91 72765 71768",
    location: "Bengaluru, Karnataka, India",
    website: "",
    linkedin: "www.linkedin.com/in/sarth1964",
    github: "",
    summary:
      "Senior Technical Product Manager with 7+ years of experience bridging deep technical architecture with user-centric enterprise SaaS. Proven track record of steering 0-to-1 AI/ML products, driving cloud infrastructure strategy, and delivering $50M+ in client impact. Combines an MBA from IIM Indore with hands-on software engineering expertise to align cross-functional engineering teams, optimize cloud governance, and design intuitive, high-scale digital user journeys.",
  },
  experience: [
    {
      id: "1",
      role: "Senior Product Manager",
      company: "Optum, UHG",
      location: "Bengaluru",
      startDate: "2025-03",
      endDate: "",
      isCurrent: true,
      highlights: [
        "Accelerated enterprise cloud and AI adoption by launching a multi-cloud Service Governance application that introduced self-service workflows for new service requests and AI model governance.",
        "Standardized multi-cloud adoption and centralized consumption alerting by delivering a unified UI experience for cloud onboarding across Cloud Service Providers (CSPs).",
        "Identified strategic migration opportunities and optimized infrastructure by analyzing 1,991 cloud databases, including 578 deployed on NextGen networking.",
        "Established robust, enterprise-wide automated guardrails for IAM, data residency, and encryption using Azure Policy, AWS SCPs, and GCP Org Policies.",
      ],
    },
    {
      id: "2",
      role: "Product Manager",
      company: "Optum, UHG",
      location: "Bengaluru",
      startDate: "2023-11",
      endDate: "2025-03",
      isCurrent: false,
      highlights: [
        "Saved 30+ minutes per Prior Authorization (PA) case and reduced manual job-aid searches by leading the 0-to-1 launch of an AI-powered chatbot based on deep user workflow analysis.",
        "Boosted system usability and response times by redesigning 150K+ clinical guidelines, collaborating closely with clinicians and technical architects to structure data for AI models.",
        "Streamlined user journeys and improved efficiency across 8M+ annual cases by directing comprehensive UI/UX redesign initiatives for PA workflows.",
        "Improved operational resilience, security, and scalability by migrating a high-volume fax system (10K+/hr) to a cloud-native architecture.",
        "Achieved $100K in annual cost savings and reduced inbound call volume by integrating Case Status & Eligibility Services with external vendor APIs.",
      ],
    },
    {
      id: "3",
      role: "Product Analyst",
      company: "Optum, UHG",
      location: "Bengaluru",
      startDate: "2022-04",
      endDate: "2023-11",
      isCurrent: false,
      highlights: [
        "Enabled $50M+ in annual client savings by embedding predictive and preventive analytics into quality measurement workflows.",
        "Achieved $100K+ in operational savings and ensured NCQA compliance by managing a portfolio of 300+ HEDIS, AMP, and PQA quality measures.",
        "Reduced cognitive load for OQM users and improved case resolution efficiency by conceptualizing and piloting GenAI-driven workflow optimizations.",
        "Improved hybrid measure performance through medical record review by contributing to the development of an NLP-powered abstraction platform.",
      ],
    },
    {
      id: "4",
      role: "Product Management Intern",
      company: "Manomay Consultancy Services",
      location: "Hyderabad",
      startDate: "2021-04",
      endDate: "2021-06",
      isCurrent: false,
      highlights: [
        "Shortened the cash conversion cycle by 30% by researching and recommending vendor solutions for document digitization and invoice automation.",
        "Identified digital transformation opportunities by conducting comprehensive market research across 20+ Caribbean insurers.",
      ],
    },
    {
      id: "5",
      role: "Software Engineer",
      company: "Druva Data Solutions",
      location: "Pune",
      startDate: "2019-05",
      endDate: "2019-10",
      isCurrent: false,
      highlights: [
        "Reduced reporting effort by 30% and improved data visibility for 10K+ users by building a centralized dashboard spanning multiple Druva enterprise products.",
        "Achieved 20% cost savings through optimized execution by designing and deploying REST APIs on AWS Lambda and API Gateway.",
      ],
    },
    {
      id: "6",
      role: "Associate Software Engineer",
      company: "Veritas Technologies LLC",
      location: "Pune",
      startDate: "2017-07",
      endDate: "2019-05",
      isCurrent: false,
      highlights: [
        "Recovered $400K+ in perpetual licenses by implementing proactive telemetry services to detect and prevent revenue leakage.",
        "Improved system scalability by 20% and boosted performance by migrating key architectural components to Golang.",
        "Strengthened security and reduced errors by 25% by delivering 6 critical license authentication features in collaboration with 10+ cross-functional product teams.",
      ],
    },
  ],
  education: [
    {
      id: "1",
      degree: "MBA",
      institution: "Indian Institute of Management Indore (IIM-Indore)",
      location: "Indore",
      startDate: "2020-06",
      endDate: "2022-05",
      gpa: "",
    },
    {
      id: "2",
      degree: "Advance Diploma in AI Product Management",
      institution: "IIT Madras",
      location: "Chennai",
      startDate: "",
      endDate: "",
      gpa: "",
    },
    {
      id: "3",
      degree: "B.Tech in Information Technology",
      institution: "College of Engineering Pune (COEP)",
      location: "Pune",
      startDate: "2013-08",
      endDate: "2017-05",
      gpa: "",
    },
  ],
  skills: [
    {
      category: "Product Management",
      items: [
        "0-to-1 Product Lifecycle",
        "Go-To-Market Strategy",
        "Product Roadmap",
        "User-Centric Design",
        "Agile & Scrum",
        "A/B Testing",
        "Stakeholder Management",
        "FinOps",
      ],
    },
    {
      category: "Technical",
      items: [
        "Cloud Native Architecture (AWS, Azure, GCP)",
        "AI/ML",
        "NLP",
        "Prompt Engineering",
        "SQL",
        "Python",
        "Golang",
        "REST APIs",
      ],
    },
    { category: "Data & Analytics", items: ["Tableau", "PowerBI", "Predictive Analytics"] },
  ],
  certifications: [
    { name: "Prompt Engineering with ChatGPT", issuer: "LinkedIn Learning", date: "2025" },
    {
      name: "Product Management: Building a Product Roadmap",
      issuer: "LinkedIn Learning",
      date: "2025",
    },
  ],
};

export type ResumeData = typeof resumeData;
